### ISSUE TITLE
A reference file has expired or been deleted

### ISSUE THREAD

**Issue by 3usi9** [jeffpar/pcjs.v1#81]
`pcjs/pubs/pc/software/tools/microsoft/masm/5.00/MASM 5.00 Programmer’s Guide`
This file has been deleted and cannot download anymore

**Comment by jeffpar** [comment]
Thanks -- should be fixed now.

**Comment by 3usi9** [comment]
No, still can't download it. The webpage told me that this item might not exist or is no longer available.

> ![screenshot](https://user-images.githubusercontent.com/20506941/76692939-bf5fa500-6698-11ea-9a28-96421fcde525.png)

From this page
``https://github.com/jeffpar/pcjs/tree/master/pubs/pc/software/tools/microsoft/masm/5.00``
->
``MASM 5.00 Programmer's Guide``
->
``https://1drv.ms/b/s!ArcO_mFRe1Z9gqFg0Tgchni_xFP47g?e=WzHExg``

**Comment by mgarlanger** [comment]
I'm seeing the same error. All the other links to oneDrive on that page works, only the Programmer's Guide is giving the error.

**Comment by jeffpar** [comment]
When I load this [page](https://www.pcjs.org/pubs/pc/software/tools/microsoft/masm/5.00/), it shows this [link](https://1drv.ms/b/s!ArcO_mFRe1Z9heBnDrC9pXwVwxYw1A?e=OZkNow), which works for me. Maybe it's a cache issue?

The change to the MASM 5.0 README occurred [here](https://github.com/jeffpar/pcjs/commit/b20ea1cbad3d39e03f652d48a5abe0d16b2df601#diff-5dac2fa13969cea5387b32a3a37a5ff7).

**Comment by 3usi9** [comment]
Ah, the link on `pcjs.org` has changed, but in github [repository]( https://github.com/jeffpar/pcjs/tree/master/pubs/pc/software/tools/microsoft/masm/5.00) this link is still unchanged and dead, anyway, it can be download now

**Comment by jeffpar** [comment]
Yeah, I should have updated the master branch, but I've been taking shortcuts because I'm working on a site redesign. I'll merge back to the master branch soon. Thanks for the followup.
